// From Bambu Studio
FILAMENT_COLOR__BAMBU__PETG_CF__BLACK = "#161616";
FILAMENT_COLOR__BAMBU__PETG_HF__CREAM = "#F9DFB9";
FILAMENT_COLOR__BAMBU__PLA_BASIC__BLACK = "#000000";
FILAMENT_COLOR__BAMBU__PLA_BASIC__GREEN = "#00AE42";
FILAMENT_COLOR__BAMBU__PLA_BASIC__RED = "#FF0000";
FILAMENT_COLOR__BAMBU__PLA_BASIC__SILVER = "#A6A9AA";
FILAMENT_COLOR__BAMBU__PLA_BASIC__WHITE = "#FFFFFF";
FILAMENT_COLOR__BAMBU__PLA_CF__BURGUNDY = "#951E23";
FILAMENT_COLOR__BAMBU__PLA_CF__JEANS_BLUE = "#6E88BC";
FILAMENT_COLOR__BAMBU__PLA_CF__LAVA_GRAY = "#4D5054";
FILAMENT_COLOR__BAMBU__PLA_CF__MATCHA_GREEN = "#5C9748";
FILAMENT_COLOR__BAMBU__PLA_CF__PURPLE = "#69398E";
FILAMENT_COLOR__BAMBU__PLA_CF__BLACK = "#000000";
FILAMENT_COLOR__BAMBU__PLA_MARBLE__WHITE = "#F7F3F0";
FILAMENT_COLOR__BAMBU__PLA_MATTE__DARK_BLUE = "#042F56";
FILAMENT_COLOR__BAMBU__PLA_SILK__BLUE_MAGENTA = "#0047BB";
FILAMENT_COLOR__BAMBU__PLA_SILK__PINK_GOLD = "#F79D54";

// Non-Bambu
FILAMENT_COLOR__CREALITY__PLA__WOOD = "#CFAB76";
FILAMENT_COLOR__ELEGOO__PLA_PLUS__PINK = "#F08DBF";
FILAMENT_COLOR__ELEGOO__PLA_PLUS__GALAXY_PEACOCK = "#05484C";
FILAMENT_COLOR__ELEGOO__PLA_PLUS__GALAXY_PURPLE = "#2A1967";
FILAMENT_COLOR__ELEGOO__SILK_PLA__CORAL = "#E46857";
